### PR TITLE
Prac 5 code review request

### PR DESCRIPTION
**Pull request by XavierKoen**
Please check formatting, naming and logic @TristanBowen

### CODE REVIEW

**Comment by TristanBowen** [comment]
For the emails.py your formating and logic is good, and the program never crashed, however you could try and check the email for numbers ect.
For example, I entered 123456 for the email, and as you know, that is not a valid email.
Although it didn't ask this in the prac, in future, you could use code simelar to the password checker, where you check each charactore and see if it is a valid email address, so has the @ symble, and the . 
Overall, was prety good.

**Comment by TristanBowen** [comment]
For the hex_colours.py, I was really impressed.
Not only is the formating, and logic good, but you have made it so that the user can enter upper case, and lower case, and the program won't crash.
Great job!

**Comment by TristanBowen** [comment]
The state_names.py and the word_occurrences.py are all good, in terms of formating, and logic.

**Comment by XavierKoen** [comment]
Thank you for the kind and constructive feedback. Those are excellent refinement ideas you've given me for emails.py and will be sure to add them before merging this branch to master.

**Pull request merged**
